<?php

declare(strict_types=1);

/**
 * @file
 * Provides a learning opportunity specification entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

function occ_entities_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle)
{
  if ($entity_type->id() === 'occ_los' && $bundle === 'course') {
    if (isset($fields['course__related_programme'])) {
      $fields['course__related_programme']->addConstraint('UniqueProgrammeReference', []);
      $fields['course__related_programme']->addConstraint('YearFormat', []);
      // TODO: figure out if constraint is possible
      // $fields['course__related_programme']->addConstraint('YearMatchesProgramme', []);
      $fields['course__related_programme']->addConstraint('ProgrammeHeiMatchesLos', []);
    }

    if (isset($fields['course__prerequisite_course'])) {
      $fields['course__prerequisite_course']->addConstraint('CourseHeiMatchesLos', []);
    }

    if (isset($fields['course__academic_term'])) {
      $fields['course__academic_term']->addConstraint('IntOverGreaterOrEqualPositiveInt', []);
    }

    if (isset($fields['course__local_classification'])) {
      $fields['course__local_classification']->addConstraint('ValueAndTypeProvided', []);
    }
  }

  if ($entity_type->id() == 'occ_los' && $bundle == 'programme') {
    if (isset($fields['programme__eqf_level'])) {
      $fields['programme__eqf_level']->addPropertyConstraints('value', [
        'Range' => [
          'min' => 5,
          'max' => 8,
        ]
      ]);
    }

    if (isset($fields['programme__length'])) {
      $fields['programme__length']->addConstraint('PositiveIntOverInt', []);
    }
  }
}

/**
 * Implements hook_theme().
 */
function occ_entities_theme(): array
{
  return [
    'occ_los' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for learning opportunity specification templates.
 *
 * Default template: occ-los.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the learning opportunity specification information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_occ_los(array &$variables): void
{
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
// TODO: review
function occ_entities_user_cancel($edit, UserInterface $account, $method): void
{
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish learning opportunity specifications.
      $storage = \Drupal::entityTypeManager()->getStorage('occ_los');
      $occ_los_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($occ_los_ids) as $occ_los) {
        /** @var \Drupal\occ_entities\Entity\LearningOpportunitySpecification $occ_los */
        $occ_los->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize learning opportunity specifications.
      $storage = \Drupal::entityTypeManager()->getStorage('occ_los');
      $occ_los_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($occ_los_ids) as $occ_los) {
        /** @var \Drupal\occ_entities\Entity\LearningOpportunitySpecification $occ_los */
        $occ_los->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
// TODO: review
function occ_entities_user_predelete(UserInterface $account): void
{
  // Delete learning opportunity specifications that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('occ_los');
  $occ_los_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($occ_los_ids)
  );
  // Delete old revisions.
  $occ_los_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  // TODO: check deprecation notice
  foreach (array_keys($occ_los_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
