<?php

declare(strict_types=1);

/**
 * @file
 * Adds reference selection handlers to occ_los entities.
 */

/**
 * Adds entity reference selection handler to both Programme and Course ounit base field.
 *
 * @param mixed $fields
 * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
 * @return void
 */
function occ_entity_reference_selection_entity_base_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type)
{
  if ($entity_type->id() === 'occ_los') {
    if (isset($fields['ounit'])) {
      $fields['ounit']->setSetting('handler', 'occ_entity_reference_selection_ounit_selection');
    }

    if (isset($fields['hei'])) {
      $fields['hei']
        ->setSetting('handler', 'ewp_institutions_user')
        ->setSetting('handler_settings', [
          'negate' => FALSE,
          'show_all' => FALSE,
        ]);
    }
  }
}

// Activates select own HEIs Programmes only for course__related_programme bundle field
function occ_entity_reference_selection_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle)
{
  if ($entity_type->id() === 'occ_los' && $bundle === 'course') {
    if (isset($fields['course__related_programme'])) {
      $fields['course__related_programme']->setSetting('handler', 'occ_entity_reference_selection_programme_selection');
    }
  }
}
